### ISSUE TITLE
Design - Homepage UI

### ISSUE THREAD

**Issue by Mehrabbruno** [wizardamigos/new-webpage#2]
## `Todo`

- [x] Design Homepage UI
   - `@input` 📦 [stickers](https://github.com/wizardamigos/assets/blob/main/Wizard%20Designs/Wizard_Amigos_-_Colour_Pallette_-_2022.pdf) from [assets](https://github.com/wizardamigos/assets/tree/main/Wizard%20Designs)
   - [x] design a above the fold section
   - `@output` 📦 [homepage_v0.0.1](https://www.figma.com/file/MHvLoXW15sF6HupfLJw6vr/wizard_amigos_homepage?type=design&node-id=131-1972&mode=design&t=rFk9ydw6LclxWWFe-4) from [comment]()

---

- [x] Updated homepage_v0.0.1
   - `@input` 📦 [homepage_v0.0.1](https://www.figma.com/file/MHvLoXW15sF6HupfLJw6vr/wizard_amigos_homepage?type=design&node-id=131-1972&mode=design&t=rFk9ydw6LclxWWFe-4)
   - `@input` 📦 [terminal_v0.0.2]() from 
   - [x] design about us section
   - [x] design past events
   - [x] design photos
   - `@output` 📦 [homepage_v0.0.2](https://www.figma.com/file/MHvLoXW15sF6HupfLJw6vr/wizard_amigos_homepage?type=design&node-id=132-1994&mode=design&t=rFk9ydw6LclxWWFe-4) from [comment]()

**Comment by Mehrabbruno** [comment]
### tasks - `2024.02.22`

- Updated homepage_v0.0.2 - `3h2min`
   - update homepage UI
   - record worklog and update tasks - 
   - `@output` 📦 [homepage_v0.0.3](https://www.figma.com/file/MHvLoXW15sF6HupfLJw6vr/wizard_amigos_homepage?type=design&node-id=182-4623&mode=design&t=IaKkUeaNrpqWgbhY-4)

---

## worklog 

[worklog-196](https://youtu.be/lSiP4Fc0dzU)


---

## feedback


---

## proposal
