### ISSUE TITLE
Add - sparkle-effect component

### ISSUE THREAD

**Issue by alyhxn** [wizardamigos/new-webpage#20]
## `todo`

- [x] Add - sparkle-effect component
   - [x] Added sparkle effect code as given by Serapath
   - [x] Some changes in code to make it work
   - `@output` :package: [sparkle_effect_v0.0.1](https://github.com/wizardamigos/new-webpage/commit/a045a128cc107b7110b8b2fc89c120a19b8141f8#diff-65dfefa2c7c3b351a2fb2ef69716044a48a49504c92ee4dbe0a8ba7040c3fa46) from [comment](https://github.com/wizardamigos/new-webpage/issues/20#issuecomment-2030767361)

**Comment by alyhxn** [comment]
### tasks - `2024.04.02`

- Add - sparkle-effect component
   - Added sparkle effect code as given by Serapath - `5min`
   - Some changes in code to make it work - `20min`
   - Changed import as in feedback - `5min`
   - Logged tasks - `5min`
   - `@output` :package: [sparkle_effect_v0.0.1](https://github.com/wizardamigos/new-webpage/commit/a045a128cc107b7110b8b2fc89c120a19b8141f8#diff-65dfefa2c7c3b351a2fb2ef69716044a48a49504c92ee4dbe0a8ba7040c3fa46)
 
---
### Worklog
I have not added styling and communication functions as they are not required in any case. So there is almost no change in the code sparkle-effect.

---
### Feedback

---
### Proposal

**Comment by serapath** [comment]
**feedback `2024.04.02`**

interesting solution to just `require('sparkle-effect/sparkle-effect.js')` :-)

you have two othe alternatives so you can just `require('sparkle-effect')`
* either make `src/node_modules/sparkle-effect/index.js`
* or create `src/node_modules/sparkle-effect/package.json` and add `{ "main": "./sparkle-effect.js" }`

we usually do the second option, because having many files open named after their component is nicer than having many files in your editor tabs all called `index.js` :-)

---

Other than that. Looks great, but one thing I am confused about is, that the **pull request** you made comes from https://github.com/alyhxn/wizard-amigos-webpage

This page should probably have a `README.md` that more or less copies and adapts the README from our current website.

Additionally, it has a preview page, but interestingly, the sparkles don't show on that page. Is that page up to date? You might sometimes need to add a commit `update bundle.js` by running `npm run build` so browserify creates the latest bundle file for you to commit :-)
