### ISSUE TITLE
Design - timeline UI

### ISSUE THREAD

**Issue by Mehrabbruno** [wizardamigos/new-webpage#3]
## `Todo`

- [x] Design timeline UI
   - [x] design the timeline UI using the dat-ecosystem timeline UI
   - [x] design in dark theme
   - `@output` 📦 [timeline_v0.0.1](https://www.figma.com/file/MHvLoXW15sF6HupfLJw6vr/wizard_amigos_homepage?type=design&node-id=132-2016&mode=design&t=rFk9ydw6LclxWWFe-4) from [comment]()

---

- [x] Updated timeline_v0.0.1
   - `@input` 📦 [timeline_v0.0.1](https://www.figma.com/file/MHvLoXW15sF6HupfLJw6vr/wizard_amigos_homepage?type=design&node-id=132-2016&mode=design&t=rFk9ydw6LclxWWFe-4) from 
   - [x] update the design in light theme
   - [x] add a pop-up overlay for event info
   - `@output` 📦 [timeline_v0.0.2](https://www.figma.com/file/MHvLoXW15sF6HupfLJw6vr/wizard_amigos_homepage?type=design&node-id=132-2453&mode=design&t=rFk9ydw6LclxWWFe-4) from [comment]()

**Comment by Mehrabbruno** [comment]
### tasks - `2024.02.22`

- Design timeline UI - `2h24min`
   - design the timeline UI using the dat-ecosystem timeline UI
   - design in dark theme
   - `@output` 📦 [timeline_v0.0.1](https://www.figma.com/file/MHvLoXW15sF6HupfLJw6vr/wizard_amigos_homepage?type=design&node-id=132-2016&mode=design&t=rFk9ydw6LclxWWFe-4)

---

- Updated timeline_v0.0.1 - `58min`
   - update the design in light theme
   - add a pop-up overlay for event info
   - `@output` 📦 [timeline_v0.0.2](https://www.figma.com/file/MHvLoXW15sF6HupfLJw6vr/wizard_amigos_homepage?type=design&node-id=132-2453&mode=design&t=rFk9ydw6LclxWWFe-4)

---

## worklog 

[worklog-195](https://youtu.be/VxKNzA9M9a8)

---

## feedback

---

## proposal
