### ISSUE TITLE
Extract - events data

### ISSUE THREAD

**Issue by alyhxn** [wizardamigos/new-webpage#4]
## `Todo`

- [x] Extract events data
   - [x] Extract data using graphql
   - [x] Clean the data
   - @`output` :package: (events_data_v0.0.1)[https://drive.google.com/file/d/15EEwyDGP-ip8W9EgI-caYtGtjHDIPNYZ/view?usp=sharing] from (comment)

**Comment by alyhxn** [comment]
### tasks - 2024.02.23

- Extract events data - `1h20min`
   - Extract data using graphql
   - Clean the data
   - @`output` :package: [events_data_v0.0.1](https://drive.google.com/file/d/15EEwyDGP-ip8W9EgI-caYtGtjHDIPNYZ/view?usp=sharing)

**Comment by ninabreznik** [comment]
@alyhxn Can you already upload the data in this repo!

**Comment by alyhxn** [comment]
### tasks - 2024.02.23

- Extract events data - `15min`
   - Updated data to match the timeline component
   - Created and logged tasks - `4min`
   - @`output` :package: [events_data_v0.0.2](https://github.com/wizardamigos/new-webpage/commit/e2e8d43213621f9cace46b5c7b8b58fcbd1b555f#diff-b8b1203bc269c67f71f8c3ce80a41da8ed415b72e20610e7e0a59aebab70caf6)

---

### worklog

[worklog-198](https://youtu.be/A1hAM6yqabw)

---

### feedback

---

### proposals
