### ISSUE TITLE
Extract - event images

### ISSUE THREAD

**Issue by alyhxn** [wizardamigos/new-webpage#5]
## `Todo`

- [x] Extract event images
   - [x] Extract links using GraphQL
   - [x] Downloaded using Python
   - `@output` :package: [event_photos_v0.0.1](https://drive.google.com/drive/folders/1vVEb9yrfQSDtGYwg5180hJ6X9qrBKDAJ) from [comment]()

**Comment by alyhxn** [comment]
### tasks - 2024.02.23

- Extract event images - 2h30min
   - Extract links using GraphQL
   - Download pictures of each event
   - `@output` :package: [event_pictures_v0.0.1](https://drive.google.com/drive/folders/1vVEb9yrfQSDtGYwg5180hJ6X9qrBKDAJ)

**Comment by ninabreznik** [comment]
@alyhxn Can we can the images to the repo?
