### ISSUE TITLE
Design - Homepage Mood-board

### ISSUE THREAD

**Issue by Mehrabbruno** [wizardamigos/new-webpage#6]
## `Todo`

- [x] Prepare homepage content and design plane
   - [x] Put together a mood-board
   - [x] Prepare a document for page copy and section
      - `@output` 📦 [page_content](https://hackmd.io/@bmEyR385TzK1cdDl54ixTw/Byiqussp6) from [comment]()
   - `@output` 📦 [moodboard_v0.0.1](https://www.figma.com/file/MHvLoXW15sF6HupfLJw6vr/wizard_amigos_homepage?type=design&node-id=220-2637&mode=design&t=ziMJzL9LwuCCwIWV-4) from [comment]()

**Comment by Mehrabbruno** [comment]
### tasks - `2024.03.11`

- Prepare homepage content and design plane 
   - Put together a mood-board
   - Prepare a document for page copy and section 
      - `@output` 📦 [page_content](https://hackmd.io/@bmEyR385TzK1cdDl54ixTw/Byiqussp6)
   - `@output` 📦 [moodboard_v0.0.1](https://www.figma.com/file/MHvLoXW15sF6HupfLJw6vr/wizard_amigos_homepage?type=design&node-id=220-2637&mode=design&t=ziMJzL9LwuCCwIWV-4)

---

## worklog 

[worklog-197](https://youtu.be/d5_l3RMsmU4)


---

## feedback


---

## proposal
