### ISSUE TITLE
Update - app_timeline Component

### ISSUE THREAD

**Issue by alyhxn** [wizardamigos/new-webpage#7]
## `todo`

- [x] Update app_timeline_v0.1.1
   - `@input` :package: [`app_timeline_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/462a57f122cb78e6318a80da40af95b4056e0ed9) from [comment](https://github.com/dat-ecosystem/website/issues/22#issuecomment-1914596886)
   - Update timeline to match wizard amigos data
   - `@output` :package: [`app_timeline_v0.1.2`](https://github.com/wizardamigos/new-webpage/commit/e2e8d43213621f9cace46b5c7b8b58fcbd1b555f#diff-31751a4239a2d948067baa01d3039ca4f773d66b4e719ee0138a2ff81cddc451) from [comment]()
  
---

- [ ] Finalize app_timeline_v0.1.?
   - [ ] code app_timeline
   - `@output` :package: `app_timeline_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.03.23`

- Update app_timeline_v0.1.1
   - Set up the project from dat-ecosystem repo - `1h`
   - Update timeline to match wizard amigos data - `30min`
   - Created and logged tasks - `20min`
   - `@output` :package: [`app_timeline_v0.1.2`](https://github.com/alyhxn/wizard-amigos-webpage/commit/d014b8f669498ffee013e856b00200863cee010a)
  
---

### worklog

[worklog - 198](https://youtu.be/A1hAM6yqabw)

---

### feedback

---

### proposals

**Comment by alyhxn** [comment]
### tasks - `2024.03.26`

- Update app_timeline_v0.1.2
   - Added lazy loading for timeline cards - `1h20min`
   - Adjusted filters and scrolling based on lazy loading - `1h`
   - Improved lazy jumping - `1h`
   - Added lazy loading fro upward scroll - `1h`
   - Created and logged tasks - `10min`
   - Recorded worklog - `10min`
   - `@output` :package: [app_timeline_v0.1.3](https://github.com/wizardamigos/new-webpage/commit/21d31f7314480ed94c617dffab05079a149acbb3#diff-31751a4239a2d948067baa01d3039ca4f773d66b4e719ee0138a2ff81cddc451)
  
---

### worklog

[worklog - 199](https://youtu.be/0fberrDF_qo)
- Now everything works smoothly.
- When a `year-filter` is clicked the cards of the specific year are directly loaded instead of loading all the cards on the way sequentially.
- Firstly, only lazy loading for scrolling down was implemented now we also have lazy loading for scrolling up because it was required to enable the last point.

---

### feedback

---

### proposals

**Comment by alyhxn** [comment]
### tasks - `2024.03.31`

- Update - app_timeline_v0.1.3
   - Clean up and added comments. - `20min`
   - Divided into submodules. - `25min`
   - Logged tasks - `7min`
   - Recorded worklog - `10min`
   - `@output` :package: [app_timeline_v0.1.4](https://github.com/wizardamigos/new-webpage/commit/b7bc2b37a9700cc8c7d4c7014b32c8e5f0f5f328#diff-31751a4239a2d948067baa01d3039ca4f773d66b4e719ee0138a2ff81cddc451)

---
### worklog
[worklog - 200](https://youtu.be/S03dF3zsEMg)
- After cleanup, the file was 650 lines
- When divided we got two files of 320 and 490 lines.
---
### feedback
---
### proposal
- I don't quite get why do we attach double shadows to most of the components.
